# Generated by Django 4.2.17 on 2025-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookinganalytics_revenuemetrics_customerinsights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Main Courses', 'Main Courses'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50)),
                ('dietary_info', models.CharField(blank=True, max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
